// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rttlyxypuvqrortwksxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dGx5eHlwdXZxcm9ydHdrc3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDk4MDAsImV4cCI6MjA2MjYyNTgwMH0.KiQ3IcwZxiX8EAYfoQorEx5m86mVo2UKKAu-NfRt6Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);